name: Build and Push Storybook Docker Image
on:
  push:
    branches:
      - main # Or your default branch
    paths-ignore:
      - "manifest/**"
      - ".vscode/**"
      - "project_templates/**"
      - ".github/**"
      - ".gitignore"
      - "sonar-project.properties"
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    paths-ignore:
      - "manifest/**"
      - ".vscode/**"
      - "project_templates/**"
      - ".github/**"
      - ".gitignore"
      - "sonar-project.properties"
  workflow_dispatch: # Optional: Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: | 
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "sanitized_ref=$(echo '${{ github.head_ref || github.ref_name }}' | tr '/' '-')" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Storybook Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}_storybook:${{ steps.vars.outputs.sha_short }},ghcr.io/${{ github.repository }}_storybook:${{ steps.vars.outputs.sanitized_ref }}
          file: ./storybook.Dockerfile # Specify your Dockerfile path